# This is a basic workflow to help you get started with Actions

name: karsajobs-pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "karsajobs" ]
  pull_request:
    branches: [ "karsajobs" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint-dockerfile:
    # The type of runner that the job will run on
    runs-on: golang:1.15-alpine

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Running hadolint to test Dockerfile
        run: docker run --rm -i hadolint/hadolint < Dockerfile
        
  test-app:
    runs-on: golang:1.15-alpine
    steps:
    - uses: actions/checkout@v3
    - name: Testing Karsajobs App
      run: go test -v -short --count=1 $(go list ./...)
      
  build-app-karsajobs:
    runs-on: ubuntu:latest
    steps:
    - uses: actions/checkout@v3
    - name: Build KarsaJobs App
      run: go test -v -short --count=1 $(go list ./...)
      
